//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36323
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Term2.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project_Term2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 为什么会需要此功能？\r\n因为每种用户具有不同的操作权限，可能无法执行某些关键性操作，即时是管理员也是会具有一定限制的。那么，此时你将需要输入超级管理员密码才能继续操作！ 的本地化字符串。
        /// </summary>
        internal static string AboutSecurity {
            get {
                return ResourceManager.GetString("AboutSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序发生了不可预料的严重错误，请将该错误报告给开发者，以便修正！ 的本地化字符串。
        /// </summary>
        internal static string ApplictionError {
            get {
                return ResourceManager.GetString("ApplictionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你当前已经在线，继续此操作将注销当前已经登陆的账户，是否要注销？ 的本地化字符串。
        /// </summary>
        internal static string ExitLogionQuestion {
            get {
                return ResourceManager.GetString("ExitLogionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \r\nF1显示帮助窗口！\r\nF2切换导航栏显示状态！\r\nF3切换工具栏显示状态！\r\nF4切换状态栏显示状态！\r\nF11切换全屏、窗口显示！ 的本地化字符串。
        /// </summary>
        internal static string HelpInfo_HotKey {
            get {
                return ResourceManager.GetString("HelpInfo_HotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此方法需要一个Int型参数表示操作类型。\r\n\t0：读取所有有效数据，\r\n\t1：按房间类型过滤数据，\r\n\t2：按房间状态过滤数据，3：双重条件过滤，4：按搜索方式 的本地化字符串。
        /// </summary>
        internal static string RoomReadError {
            get {
                return ResourceManager.GetString("RoomReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价格搜索以输入的文本作为客户可以接受的最高价格，查询结果按价格优惠程度排序 的本地化字符串。
        /// </summary>
        internal static string RoomSeacheNoPrice {
            get {
                return ResourceManager.GetString("RoomSeacheNoPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你输入的不是一个有效的整数。如果你要找日结房，请输入24，钟点房请输入1 的本地化字符串。
        /// </summary>
        internal static string RoomSeachNotInt {
            get {
                return ResourceManager.GetString("RoomSeachNotInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价格搜索以输入的文本作为客户可以接受的最高价格，查询结果按价格优惠程度排序 的本地化字符串。
        /// </summary>
        internal static string RoomSHelpPrice {
            get {
                return ResourceManager.GetString("RoomSHelpPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序外观设定已存储，下次启动时将自动载入当前设定！ 的本地化字符串。
        /// </summary>
        internal static string SettingSave {
            get {
                return ResourceManager.GetString("SettingSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验性功能出现严重的错误，外观设定无法正常保存，请重启应用程序或联系开发者！ 的本地化字符串。
        /// </summary>
        internal static string SettringSaveError {
            get {
                return ResourceManager.GetString("SettringSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户登陆失败，请检查账号和密码是否输入正确。如果确认无误依然无法正常登陆，请告知开发者！ 的本地化字符串。
        /// </summary>
        internal static string UserLoginError {
            get {
                return ResourceManager.GetString("UserLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当您看到这个提示，请您认真的检查您输入的信息。比如说账户名或密码为空，已经密码长度少于6位！ 的本地化字符串。
        /// </summary>
        internal static string UserLoginMessage {
            get {
                return ResourceManager.GetString("UserLoginMessage", resourceCulture);
            }
        }
    }
}
