//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ_To_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AccountOld
    {
        public string GUID { get; set; }
        public string ClientGUID { get; set; }
        public Nullable<System.DateTime> OperateTime { get; set; }
        public int OperateMoney { get; set; }
        public int OperatorTypeID { get; set; }
        public string OperatorGUID { get; set; }
    
        public virtual T_OperateType T_OperateType { get; set; }
    }
}
