//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ_To_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AccreditType
    {
        public T_AccreditType()
        {
            this.T_AccreditList = new HashSet<T_AccreditList>();
            this.T_StaffType = new HashSet<T_StaffType>();
        }
    
        public int ALevelID { get; set; }
        public string ALevelName { get; set; }
        public string ALevelRemark { get; set; }
        public Nullable<bool> IsValid { get; set; }
    
        public virtual ICollection<T_AccreditList> T_AccreditList { get; set; }
        public virtual ICollection<T_StaffType> T_StaffType { get; set; }
    }
}
