//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ_To_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ClientInfo
    {
        public T_ClientInfo()
        {
            this.T_ClientRoom = new HashSet<T_ClientRoom>();
        }
    
        public string GUID { get; set; }
        public Nullable<int> ClientCType { get; set; }
        public string ClientIDCard { get; set; }
        public string ClientIName { get; set; }
        public Nullable<bool> ClientSex { get; set; }
        public string ClientAdress { get; set; }
        public string ClientTel { get; set; }
        public string ClientVIPID { get; set; }
    
        public virtual T_PaperType T_PaperType { get; set; }
        public virtual ICollection<T_ClientRoom> T_ClientRoom { get; set; }
    }
}
