//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ_To_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OutInInfo
    {
        public string IOGUID { get; set; }
        public int IOWaresID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> IOCount { get; set; }
        public Nullable<int> IOUnit { get; set; }
        public string OperatorGUID { get; set; }
        public Nullable<System.DateTime> OperatorTime { get; set; }
        public string IORemark { get; set; }
    
        public virtual T_UnitType T_UnitType { get; set; }
        public virtual T_WaresType T_WaresType { get; set; }
    }
}
