//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ_To_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RoomList
    {
        public T_RoomList()
        {
            this.T_ClientRoom = new HashSet<T_ClientRoom>();
        }
    
        public string RoomID { get; set; }
        public int RoomType { get; set; }
        public int RoomState { get; set; }
        public string RoomRemark { get; set; }
        public Nullable<bool> IsValid { get; set; }
    
        public virtual ICollection<T_ClientRoom> T_ClientRoom { get; set; }
        public virtual T_RoomStateType T_RoomStateType { get; set; }
        public virtual T_RoomType T_RoomType { get; set; }
    }
}
