//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ_To_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RoomStateType
    {
        public T_RoomStateType()
        {
            this.T_RoomList = new HashSet<T_RoomList>();
        }
    
        public int StateID { get; set; }
        public string StateName { get; set; }
        public string StateColor { get; set; }
        public string StateRemark { get; set; }
        public Nullable<bool> IsValid { get; set; }
    
        public virtual ICollection<T_RoomList> T_RoomList { get; set; }
    }
}
