//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ_To_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_StaffList
    {
        public string StaffID { get; set; }
        public string StaffPwdMD5 { get; set; }
        public string StaffGuid { get; set; }
        public string StaffAccredit { get; set; }
        public Nullable<int> STypeID { get; set; }
    
        public virtual T_StaffInfo T_StaffInfo { get; set; }
        public virtual T_StaffType T_StaffType { get; set; }
    }
}
