//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ_To_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_StaffInfo
    {
        public T_StaffInfo()
        {
            this.T_StaffList = new HashSet<T_StaffList>();
        }
    
        public string StaffID { get; set; }
        public string StaffName { get; set; }
        public Nullable<bool> StaffSex { get; set; }
        public Nullable<int> StaffCouID { get; set; }
        public string StaffAdress { get; set; }
        public string StaffIdCard { get; set; }
        public Nullable<System.DateTime> StaffInDate { get; set; }
        public byte[] StaffImage { get; set; }
        public string StaffTel { get; set; }
        public bool IsValid { get; set; }
    
        public virtual ICollection<T_StaffList> T_StaffList { get; set; }
    }
}
