//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ_To_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_StaffType
    {
        public T_StaffType()
        {
            this.T_StaffList = new HashSet<T_StaffList>();
        }
    
        public int STypeID { get; set; }
        public string STypeName { get; set; }
        public Nullable<int> STypeALevelID { get; set; }
        public Nullable<bool> IsValid { get; set; }
    
        public virtual T_AccreditType T_AccreditType { get; set; }
        public virtual ICollection<T_StaffList> T_StaffList { get; set; }
    }
}
