//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ_To_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SupplierInfo
    {
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> SupplierCouID { get; set; }
        public string SupplierAdress { get; set; }
        public string SupplierTel { get; set; }
        public int SupplierTypeID { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsValid { get; set; }
    
        public virtual T_SupplierType T_SupplierType { get; set; }
    }
}
