//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ_To_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_RoomInfoAll
    {
        public string 房间编号 { get; set; }
        public int 类型编号 { get; set; }
        public string 类型名 { get; set; }
        public Nullable<int> 单价 { get; set; }
        public Nullable<long> 结算频率 { get; set; }
        public int 状态编号 { get; set; }
        public string 状态名 { get; set; }
        public string 颜色 { get; set; }
        public string 房间备注 { get; set; }
        public Nullable<bool> 有效状态 { get; set; }
    }
}
