//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ_To_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_HousingHistory
    {
        public string 记录编号 { get; set; }
        public string 客户姓名 { get; set; }
        public string 房间编号 { get; set; }
        public System.DateTime 入住时间 { get; set; }
        public Nullable<System.DateTime> 退房时间 { get; set; }
        public string 入住登记 { get; set; }
        public string 退房操作 { get; set; }
    }
}
