//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ_To_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ConsumeHistory
    {
        public string 客户编号 { get; set; }
        public string 客户姓名 { get; set; }
        public string 操作类型 { get; set; }
        public int 操作金额 { get; set; }
        public Nullable<System.DateTime> 操作时间 { get; set; }
        public string 客户名 { get; set; }
    }
}
